import { REALM_MECHANICS } from './realm-i18n.js';
import { WORLD_RULES, NPC_NAMES } from './world-rules-i18n.js';

const PRESET_TRANSLATIONS = {
  en: {
    "cinder-river": {
      head: ["Cinder River by Night", "A border city is breaking; one gift can change your fate", "The Cinder River runs backward beside Lanternwatch as a rare spirit tide rises. Common people may sense qi for the first time, while the medicine market, boat guild and old mine pull the city toward conflict. You are a young adult with a bounded gift and no ordained quest: help, bargain, flee or seize an opening, and the world will keep the consequences.", "Eastern progression fantasy", ["Border city", "Cultivation", "Gift", "Choice"], "TGN Live original"],
      system: ["Qi first sharpens perception and stamina, then becomes external force. Realm rank governs endurance, capacity and reachable danger; a gift bends only one local rule.", "A useful session may cover half a day. Breath work, medicine, practice, combat and the spirit tide can advance you, but repetition quickly fades. Every gain must unlock a usable action; at 100 progress, the current realm's breakthrough condition must still occur in the story.", [
        ["Mortal Body", "Normal adult strength; can sense qi briefly but cannot retain it.", "Can practise basic breathing and distinguish qi from blood and breath."],
        ["Qi Drawing I", "Can retain one thread of qi; endurance and recovery exceed ordinary people.", "Can sense qi deliberately, nourish the body and use the chosen gift in one short action."],
        ["Qi Drawing II", "Qi circulates through one channel; a burst can clear a high wall or overpower a guard.", "Can circulate while moving or distracted and enter low-risk spirit sites."],
        ["Qi Drawing III", "Qi briefly leaves the body, extending perception, defence or attack several steps.", "Can face minor spirits alone and approach the deep mine or the river night crossing."],
        ["Vein Condensation", "The channels form a stable circuit; an ordinary blade wound no longer stops action at once.", "Can sustain techniques, seek cultivator status and enter true sect or wilderness territory."],
      ]],
      powers: {
        "ember-hearing": ["Ember Echo", "Touch lingering warmth to hear a brief echo of its latest violent change.", "Grow from seconds of echo to layered traces usable while moving.", "Only reads limited traces on the touched object; no minds, remote sensing or prophecy. Repeated use causes ringing and imbalance."],
        "borrowed-force-seal": ["Borrowed Force Seal", "After taking a real impact, seal part of its force in your palm and release it once within ten breaths.", "Retain more of the force and turn one close exchange in your favour.", "Stores one hit only; you are still hurt, and cannot store spells, poison or force beyond your body's limit."],
        "hollow-pouch": ["Hollow Pouch Realm", "Three times daily, store one lifeless object fully covered by your palm in a still pocket and retrieve it unchanged.", "Increase size and speed for concealment, hand switches and bypassing searches.", "At most three objects; no living, burning or heavier-than-you objects."],
      },
      opening: ["South Gate medicine market, Lanternwatch", "The River Runs Backward", "Find your own path during the lockdown, attempt to draw qi and turn your gift into a cultivation beginning"],
      seed: { currency: "copper coins", inventory: { "plain-clothes": ["Worn cloth coat", "Faded but warm enough"], "copper-token": ["Mother's copper coin", "A crescent notch marks its rim"] }, relationships: { "shen-qiuhua": ["Shen Qiuhua", "medicine-market keeper"], "han-zheng": ["Han Zheng", "night-watch captain"] }, capabilities: {}, facts: ["The Cinder River reversed tonight", "Lanternwatch is under temporary lockdown", "Golden mist along the bank marks a spirit tide suitable for undisturbed qi sensing", "You know crude breathing steps but have never retained qi; awakening a gift is not entering Qi Drawing"] },
    },
    "sky-beast-isles": {
      head: ["Cloudback Isles", "Beast riders race for migrating sky routes", "Hundreds of floating islands drift with the monsoon. People travel by winged beasts, sails and brief cloud bridges; each migration season erases old routes. A bond shares fear, direction and one key skill without owning the beast. Herds, hunters and a grieving flock now converge on the harbour, and you may bond, track, escort or claim another route.", "Sky-island beast bonding", ["Floating isles", "Beast bond", "Exploration", "Sky routes"], "TGN Live original"],
      system: ["A willing cloud beast answers a heart-ring and shares senses or talents. Higher realms widen shared endurance, aerial movement and possible bonds, but the beast keeps its own will.", "Complete flights, hunts, tracking or calming sessions produce growth only when they add a cooperative action, reach new airspace or earn real trust. A breakthrough needs a stable heart-ring, a willing partner and the matching sky trial.", [
        ["Groundwalker", "Can only glide briefly with gear and cannot share a cloud beast's senses.", "Can learn signals, scent and wind-reading to seek a first willing response."],
        ["Windbound Apprentice", "Shares one sense with a small cloud beast and can cross a short island gap.", "Can scout through a partner's eyes and complete true two-way cooperation."],
        ["One-Ring Rider", "The heart-ring shares one impact and lets rider and beast turn together in rough wind.", "Can enter the Thunder Sea edge and escort or hunt independently."],
        ["Two-Ring Skywarden", "Maintains two shared talents so a group can coordinate in storms.", "Can lead migrations, contest moving routes and approach great sky beasts."],
        ["Cloudcrown Binder", "A bond can include a willing flock and sustain hours of island-to-island combat.", "Can alter migration patterns and bargain equally with island lords and beast kings."],
      ]],
      powers: {
        "shared-sky-eye": ["Shared Sky Eye", "When a cloud beast willingly meets your gaze, borrow its sight and direction briefly.", "Grow from seconds of sight to two-way coordination in flight and shared squad awareness.", "No force or control theft; fear or betrayal ends the link immediately."],
        "wild-bond": ["Wild Pact", "Understand a cloud beast's strongest desire and offer an exchange binding both sides.", "Grow from one exchange to lasting pacts and flock negotiation that opens unique routes.", "You hear only the strongest desire, not every thought, and must fulfil your side."],
        "borrowed-wing": ["Borrowed Wing", "Touch a willing partner to manifest one of its movement traits on your body.", "Grow from gliding and clinging to true flight and combinations from different partners.", "One trait at a time, limited by your realm and the partner's stamina."],
      },
      opening: ["Hatchling Harbour, Broken-Sail Isle", "The Migration Breaks Loose", "Gain your first real freedom of action in the sky before the route closes"],
      seed: { currency: "wind beads", inventory: { "glider-harness": ["Old glider harness", "Survives one short glide; avoid hard gusts at the worn straps"], "sweet-moss": ["Sweet-moss cakes", "Most young cloud beasts will pause to smell them"] }, relationships: { "mi-ya": ["Miya", "cloud-beast healer"], "kun-ge": ["Kungo", "disgraced navigator"] }, capabilities: { "short-glide": ["Short glide", "Use the old harness to cross a drop of about ten paces; rough wind is dangerous.", "Old glider harness"] }, facts: ["The migration bell rang early", "Red moss in the mirrorwing's wound comes from no local island", "The hatchling has bonded with no one"] },
    },
    "ashen-star-covenant": {
      head: ["Ashen Star Covenant", "A magic city's star gate is missing one star", "The Whiteflame city-states run lights, trains and frontier wards through inscribed magic, yet each depends on a council-controlled star gate. Grey Tower's seventh route-star has gone dark: luggage enters, travellers do not return. The academy suppresses the news, families press the gate, and a smuggler offers a shard that can rewrite one spell.", "Western magic fantasy", ["Magic", "City-states", "Star gate", "Exploration"], "TGN Live original"],
      system: ["Mages inscribe rings on the body and use mind plus materials to turn a clear intent into fire, force, shape or distance. Realm sets ring count, range and backlash tolerance.", "A session may cover hours of inscription, casting and review. Mastery requires success on a real object and a recorded reusable spell or method. Breakthroughs stabilize current rings, understand a new structure and pass a public or private test.", [
        ["Ringless Apprentice", "Uses finished charms but cannot sustain a spell alone.", "Can read basic marks and safely trigger one low-grade charm."],
        ["One-Ring Adept", "Sustains a palm-sized spell for more than ten breaths.", "Can independently ignite, push, shape or detect one concrete target."],
        ["Two-Ring Shaper", "Covers a room with a moving spell.", "Can enter academy workshops and minor ruins and create a personal charm."],
        ["Three-Ring Towerwalker", "Maintains three compatible spells and withstands a district-scale accident.", "Can pass through a nearby door, travel alone and contest city-state magic."],
        ["Star-Gate Mage", "Anchors distant coordinates and moves groups or large objects between cities.", "Can repair or seize a gate and change real distance and power between cities."],
      ]],
      powers: {
        "spell-echo": ["Spell Echo", "After watching a spell complete, reproduce it once without materials within one hour.", "Advance from copying minor spells to splitting and recombining observed structures.", "Must see the whole casting; holds one echo, never above your realm's power."],
        "living-script": ["Living Script", "One basic mark you write adjusts itself once when its object moves or breaks.", "Grow from stabilizing small items to adapting armour, doors and vehicles on site.", "It only preserves the original intent and cannot create a second spell."],
        "true-distance": ["True Distance", "While touching two visible objects, know their shortest viable path and make your next step cover two.", "Grow from room-scale sidesteps to doors, walls and star-gate positioning.", "Cannot cross an unknown lethal space and affects only your next step."],
      },
      opening: ["Lost-property hall, Grey Tower North Station", "The Seventh Star Goes Dark", "Master your first personal spell during the gate lockdown and decide how to use the disappearance clue"],
      seed: { currency: "silver shields", inventory: { "chalk-case": ["Inscription chalk case", "Six mineral chalks, enough for three basic marks"], "station-ticket": ["Void North Station ticket", "Star-gate safety rules are printed on the back"] }, relationships: { seif: ["Seif", "academy inspector"], oran: ["Oran", "clockmaker"] }, capabilities: { "read-basic-runes": ["Read basic marks", "Recognize start, stop and danger marks, but cannot yet cast alone.", "Former apprentice lessons"] }, facts: ["Grey Tower's seventh route-star went dark tonight", "The gate returns luggage but not travellers", "The academy has not disclosed the accident's scale"] },
    },
    "crimson-cauldron": {
      head: ["Crimson Cauldron Province", "Flame seeds, formulas and realms can change a life tonight", "Cultivators draw flame-breath into an inner wheel, raising strength, speed, control and access to firelands. Alchemists turn rare herbs into breakthrough chances, so clans, guilds and mercenaries fight over formulas and flame seeds. A public furnace has exploded in Southridge, releasing an ownerless blue flame into the old quarter.", "Flame cultivation and alchemy", ["Flame breath", "Alchemy", "Breakthrough", "Rare flame"], "Unofficial fan inspiration · Battle Through the Heavens growth mechanics"],
      system: ["Flame-breath enters the inner wheel, first strengthening body and fire sense, then projecting outward. Herbs, combat pressure, method insight and rare flames affect accumulation, breakthroughs and technique limits.", "A session may cover half a day to half a month depending on resources. Record material use, current realm, speed relative to normal and the new move's effect on a real object. Each step adds at most 20 progress; crossing a realm also requires its stated condition.", [
        ["Breath Stage Three", "Can sense flame-breath but remains near an ordinary fighter and cannot project fire.", "Can complete a medicinal bath and identify common herbs by energy."],
        ["Breath Stage Four", "Clearly stronger than ordinary people and can pull a vase half a foot at range.", "Can use a first pull or shock to change a struggle over an object."],
        ["Wheel Gathering One-Star", "The inner wheel forms, supporting sustained combat and brief projected flame-breath.", "Can formally study alchemy, enter mercenary firelands and face city cultivators."],
        ["Blazing Master One-Star", "Flame-breath covers several yards and protects self plus one person in fire.", "Can refine breakthrough medicine, contest a city flame and lead entry into the fire palace."],
        ["Skyborne King", "Flame wings allow flight and suppress a whole lower-rank squad.", "Can cross natural barriers, found an apothecary or challenge provincial powers."],
      ]],
      powers: {
        "ten-thousand-flames": ["Affinity of Ten Thousand Flames", "An unfamiliar flame's first touch does not burn you at once and reveals its easiest moment to tame.", "Grow from one opening to handling many flame natures for alchemy, battle and firelands.", "Only the first touch is spared; taming, realm and sustained heat cannot be skipped."],
        "pill-pattern-echo": ["Pill-Pattern Echo", "After tasting a pill, identify its most important ingredient and one failed heat step.", "Grow from spotting errors to revising and creating a personal alchemy path.", "One ingredient and one heat clue per pill, never the full formula."],
        "breakthrough-ember": ["Breakthrough Ember", "A true minor breakthrough leaves a three-day ember that can replay its burst in one move.", "Higher realms make that one burst more decisive in battle, alchemy or escape.", "One ember per breakthrough, lost when used; failure or a spoken claim creates none."],
      },
      opening: ["Old Medicine Street, Southridge City", "The Ownerless Blue Flame", "Seize one chance that can truly begin cultivation or alchemy"],
      seed: { currency: "gold coins", inventory: { "warming-tonic": ["Meridian-warming tonic", "Enough for one half-day medicinal bath, then exhausted"], "iron-palm-notes": ["Breath-Pull copied page", "Records the most basic ranged pulling exercise"] }, relationships: { "gu-yao": ["Gu Yao", "heir to a failing apothecary"], "shi-kuo": ["Shi Kuo", "one-armed mercenary"] }, capabilities: { "sense-flame": ["Sense flame-breath", "With eyes closed, locate the strongest flame-breath within several paces but not its owner.", "Breath Stage Three"] }, facts: ["The public medicine furnace exploded tonight", "An ownerless blue flame entered an old-street bathhouse", "The alchemy guild is sealing Old Medicine Street"] },
    },
    "myriad-mark-hunt": {
      head: ["Myriad-Mark Hunting Court", "Every milestone adds a new move to your true form", "Adults awaken a true form—beast, weapon, plant or stranger shape. At major thresholds, a cultivator must face a matching wild being and gain a willingly given mark or an intact core left after battle before carving a new move into that form. The academy controls safe hunting grounds while a lone thunderhorn forces a frontier village to evacuate.", "True-form progression", ["True form", "Marks", "Academy", "Ability combinations"], "Unofficial fan inspiration · Soul Land growth mechanics"],
      system: ["Training raises the true form's body, reactions and energy; marks add clear moves at major thresholds. Form-and-mark combinations define tactics, while higher rank still gives the larger foundation.", "A daily session can improve control, physique or an existing mark skill. Real growth steadies an old move or opens a new use. Major advances require enough progress, proven endurance and a compatible mark; no mark skill appears from nothing.", [
        ["First Awakening I", "The true form appears for less than a quarter hour.", "Can use its most basic bodily or object trait once."],
        ["Mark Formation X", "The form fights stably and can bear its first mark.", "Gains a true mark skill and access to formal hunting grounds and academy trials."],
        ["Dual Mark XX", "Two mark skills combine in sequence; physique can face a large beast directly.", "Can hunt independently, enter deep forbidden woods and form a personal style."],
        ["Mark Command XL", "The form covers the body or becomes fully physical across several yards.", "Can form a hunting team, contest rare cores and alter a local faction's judgment."],
        ["Crowned Mark LXX", "The true form creates a domain that suppresses lower mark skills.", "Can enter royal preserves, challenge beast kings and set a hunting court's rules."],
      ]],
      powers: {
        "dual-aspect": ["Dual-Aspect True Form", "Switch between one form that strengthens the body and one that becomes an object.", "Every mark gains a different use in each aspect, building a composable combat tree.", "Only one aspect at a time; switching interrupts the current mark skill."],
        "self-grown-mark": ["Self-Grown Mark", "No beast must die: perfect a basic action at its limit and your true form grows the matching mark.", "Turn hard-earned actions and personal history directly into mark skills.", "Each mark needs one verifiable limit achievement; safe repetition cannot farm it."],
        "trait-graft": ["Borrowed Trait", "Touch an unabsorbed core to test one of its moves for ten breaths.", "Use trials to judge compatibility, then borrow rare moves at decisive moments.", "One move only, not retained; overload ends it immediately."],
      },
      opening: ["Hunting Court exam shed, Green Oak Village", "The Thunderhorn Never Entered", "Prove one real use of your true form and find your first genuine mark opportunity"],
      seed: { currency: "mark coins", inventory: { "training-brace": ["Training bracer", "Absorbs one loss-of-control impact from a newly awakened form"], "salted-meat": ["Salted meat", "One day's trail food or bait for an ordinary beast"] }, relationships: { "du-heng": ["Du Heng", "Green Oak village head"], "a-chi": ["A Chi", "young hunter"] }, capabilities: { "manifest-form": ["Manifest true form", "Hold the chosen form for over ten breaths and use its simplest trait.", "First Awakening I"] }, facts: ["The academy cancelled Green Oak's admission places", "A thunderhorn blocks the only road but has not attacked villagers", "The second mountain thunder came without a beast's roar"] },
    },
  },
};

const LANGUAGE_TERMS = {
  fr: {
    "cinder-river": ["La Rivière des Braises", "Une cité frontière vacille ; un don peut changer votre destin", "La Rivière des Braises remonte près de Veille-Lanterne tandis qu'une marée spirituelle s'élève. Le marché des remèdes, les bateliers et l'ancienne mine entraînent la ville vers le conflit. Jeune adulte doté d'un pouvoir limité, vous pouvez aider, négocier, fuir ou saisir une occasion : chaque choix laisse des conséquences.", "Fantasy de cultivation orientale", ["Cité frontière", "Cultivation", "Don", "Choix"]],
    "sky-beast-isles": ["Îles du Dos-des-Nuages", "Les dresseurs se disputent des routes célestes migrantes", "Des centaines d'îles flottantes dérivent avec la mousson. On voyage par bêtes ailées, voiles et ponts de nuages éphémères. Un pacte partage peur, orientation et talent sans posséder la bête. Troupeaux, chasseurs et une harde en deuil convergent vers le port.", "Îles célestes et pactes bestiaux", ["Îles flottantes", "Pacte bestial", "Exploration", "Routes célestes"]],
    "ashen-star-covenant": ["Pacte de l'Étoile Cendrée", "La porte stellaire a perdu une étoile", "Les cités de Flamme-Blanche vivent de magie gravée et de portes stellaires contrôlées par le conseil. La septième étoile de Tour-Grise s'est éteinte : les bagages entrent, les voyageurs ne reviennent pas. L'académie étouffe l'affaire tandis qu'un contrebandier vend un éclat capable de réécrire un sort.", "Fantasy magique occidentale", ["Magie", "Cités-États", "Porte stellaire", "Exploration"]],
    "crimson-cauldron": ["Province du Chaudron Écarlate", "Flammes, formules et royaumes changent une vie", "Les pratiquants absorbent le souffle de flamme dans une roue intérieure. Les alchimistes transforment les plantes rares en chances de percée, et clans, guildes et mercenaires se disputent graines de feu et formules. À Crête-du-Sud, un four public explose et libère une flamme bleue sans maître.", "Cultivation de flamme et alchimie", ["Souffle de flamme", "Alchimie", "Percée", "Flamme rare"]],
    "myriad-mark-hunt": ["Cour de Chasse aux Mille Marques", "Chaque étape ajoute un geste à votre forme véritable", "À l'âge adulte, chacun éveille une forme véritable. Aux grands seuils, il faut affronter un être compatible et recevoir une marque offerte ou un noyau intact après combat pour graver un nouveau geste. L'académie contrôle les zones sûres tandis qu'un corne-foudre isolé force un village à évacuer.", "Progression par forme véritable", ["Forme véritable", "Marques", "Académie", "Combinaisons"]],
  },
  es: {
    "cinder-river": ["Río de Brasas Nocturno", "Una ciudad fronteriza cae; un don puede cambiar tu destino", "El Río de Brasas corre al revés junto a Vigilia y surge una marea espiritual. El mercado de medicinas, el gremio fluvial y la vieja mina empujan la ciudad al conflicto. Eres una persona adulta joven con un don limitado: ayuda, negocia, huye o aprovecha la ocasión, y cada decisión dejará consecuencias.", "Fantasía oriental de cultivo", ["Ciudad fronteriza", "Cultivo", "Don", "Decisión"]],
    "sky-beast-isles": ["Islas Lomo de Nube", "Los jinetes compiten por rutas celestes migratorias", "Cientos de islas flotantes derivan con el monzón. Se viaja con bestias aladas, velas y puentes de nube breves. Un vínculo comparte miedo, orientación y una destreza sin poseer a la bestia. Pastores, cazadores y una bandada afligida convergen en el puerto.", "Islas flotantes y vínculos bestiales", ["Islas flotantes", "Vínculo bestial", "Exploración", "Rutas celestes"]],
    "ashen-star-covenant": ["Pacto de la Estrella Ceniza", "A la puerta estelar le falta una estrella", "Las ciudades de Llama Blanca dependen de magia inscrita y puertas estelares controladas por el consejo. La séptima estrella de Torre Gris se apagó: entra equipaje, pero no regresan viajeros. La academia oculta el accidente mientras un contrabandista vende un fragmento capaz de reescribir un hechizo.", "Fantasía mágica occidental", ["Magia", "Ciudades-estado", "Puerta estelar", "Exploración"]],
    "crimson-cauldron": ["Provincia del Caldero Carmesí", "Semillas de fuego, fórmulas y reinos cambian una vida", "Los cultivadores absorben aliento ígneo en una rueda interior. Los alquimistas convierten hierbas raras en oportunidades de avance, por lo que clanes, gremios y mercenarios disputan fórmulas y llamas. Un horno público explota en Cresta Sur y libera una llama azul sin dueño.", "Cultivo ígneo y alquimia", ["Aliento ígneo", "Alquimia", "Avance", "Llama rara"]],
    "myriad-mark-hunt": ["Corte de Caza de las Mil Marcas", "Cada hito añade un movimiento a tu forma verdadera", "Al llegar a la adultez todos despiertan una forma verdadera. En cada gran umbral deben afrontar a un ser afín y obtener una marca voluntaria o un núcleo intacto tras combatir para grabar un movimiento nuevo. La academia controla las zonas seguras mientras un cuernotrueno obliga a evacuar una aldea.", "Progresión de forma verdadera", ["Forma verdadera", "Marcas", "Academia", "Combinaciones"]],
  },
  ar: {
    "cinder-river": ["نهر الجمر ليلًا", "مدينة حدودية توشك أن تنهار، وموهبة واحدة قد تغيّر المصير", "يجري نهر الجمر عكس تياره قرب مدينة سراج الليل مع صعود موجة من الطاقة الروحية. يدفع سوق الدواء ونقابة القوارب والمنجم القديم المدينة نحو الصراع. أنت شاب بالغ بموهبة محدودة، بلا مهمة مفروضة: ساعد أو فاوض أو اهرب أو اغتنم الفرصة، ولكل اختيار أثر حقيقي.", "فانتازيا زراعة شرقية", ["مدينة حدودية", "زراعة", "موهبة", "اختيار"]],
    "sky-beast-isles": ["جزر ظهور السحاب", "فرسان الوحوش يتنافسون على طرق سماوية مهاجرة", "تنجرف مئات الجزر الطافية مع الرياح الموسمية، ويسافر الناس بوحوش مجنحة وأشرعة وجسور سحاب قصيرة العمر. تشارك الرابطة الخوف والاتجاه وموهبة واحدة من دون امتلاك الوحش. تتقاطع مصالح الرعاة والصيادين وقطيع فقد صغيره عند الميناء.", "جزر طافية وروابط الوحوش", ["جزر طافية", "رابطة وحش", "استكشاف", "طرق سماوية"]],
    "ashen-star-covenant": ["عهد النجمة الرمادية", "بوابة مدينة السحر فقدت نجمة", "تعتمد مدن اللهب الأبيض على السحر المنقوش والبوابات النجمية التي يسيطر عليها المجلس. انطفأت النجمة السابعة في البرج الرمادي: تدخل الأمتعة ولا يعود المسافرون. تخفي الأكاديمية الحادث بينما يعرض مهرّب شظية تعيد صياغة تعويذة واحدة.", "فانتازيا سحرية غربية", ["سحر", "مدن مستقلة", "بوابة نجمية", "استكشاف"]],
    "crimson-cauldron": ["إقليم المرجل القرمزي", "بذور النار والوصفات والمراتب قد تغيّر الحياة الليلة", "يدخل الممارسون نفس اللهب في عجلة داخلية، فيزداد الجسد والسرعة والسيطرة على النار. يحوّل الكيميائيون الأعشاب النادرة إلى فرص اختراق، فتتنازع العشائر والنقابات والمرتزقة على اللهب والوصفات. انفجر فرن عام في مدينة التلال وأطلق لهبًا أزرق بلا مالك.", "زراعة اللهب والكيمياء", ["نفس اللهب", "كيمياء", "اختراق", "لهب نادر"]],
    "myriad-mark-hunt": ["ساحة صيد الأختام المتعددة", "كل محطة نمو تضيف حركة إلى هيئتك الأصلية", "يوقظ كل بالغ هيئة أصلية: وحشًا أو سلاحًا أو نباتًا أو شكلًا غريبًا. عند كل عتبة كبرى يجب مواجهة كائن متوافق ونيل ختم يمنحه طوعًا أو نواة سليمة بعد القتال لنقش حركة جديدة. تحتكر الأكاديمية مناطق الصيد الآمنة بينما يجبر وحش قرن الرعد قرية على الإخلاء.", "تطور الهيئة الأصلية", ["هيئة أصلية", "أختام", "أكاديمية", "تركيب القدرات"]],
  },
};

const GENERIC_TRANSLATIONS = {
  fr: {
    system: ["Le rang fixe l'endurance, la réserve d'énergie et les zones accessibles ; le don ne modifie qu'une règle locale.", "Une séance complète peut condenser des heures ou une journée. Chaque progrès doit donner une action utilisable ; une percée exige encore sa condition réelle dans le récit."],
    realms: [
      ["Novice", "Capacités proches d'un adulte ordinaire ; l'énergie reste instable.", "Peut apprendre le geste de base et reconnaître la source d'énergie."],
      ["Premier rang", "L'énergie devient stable et améliore nettement l'endurance.", "Peut employer le don choisi dans une action courte et concrète."],
      ["Deuxième rang", "Peut maintenir l'énergie en mouvement et dépasser un adversaire ordinaire.", "Peut entrer dans une zone de faible danger et agir sans assistance."],
      ["Troisième rang", "L'énergie agit à plusieurs pas et soutient plusieurs usages compatibles.", "Peut affronter seul une menace mineure et ouvrir des routes plus risquées."],
      ["Rang supérieur", "La puissance reste stable durant un long affrontement et domine les rangs inférieurs.", "Peut franchir les grands obstacles et négocier avec les puissances du monde."],
    ],
    powers: {
      "cinder-river": [["Écho de braise", "Toucher une chaleur résiduelle révèle le bref écho de son dernier changement violent.", "L'écho devient plus long, plus précis et utilisable en mouvement.", "Objet touché seulement ; ni pensée, ni vision lointaine, ni avenir. L'usage répété désoriente."], ["Sceau de force empruntée", "Après un choc réel, enfermer une partie de sa force dans la paume et la libérer une fois sous dix souffles.", "Conserver davantage de force et retourner un échange rapproché.", "Un seul choc ; le corps est tout de même blessé, sans sort, poison ni force insoutenable."], ["Poche du vide", "Trois fois par jour, ranger un objet inerte couvert par la paume dans un espace immobile.", "Augmenter taille et vitesse pour cacher, échanger ou franchir un contrôle.", "Trois objets au plus ; rien de vivant, en feu ou plus lourd que soi."]],
      "sky-beast-isles": [["Œil du ciel partagé", "Une bête consentante partage brièvement sa vue et son sens de l'orientation.", "De quelques secondes à une coordination réciproque en vol.", "Aucune contrainte ; peur ou trahison coupe aussitôt le lien."], ["Pacte sauvage", "Comprendre le désir le plus fort d'une bête et proposer un échange obligatoire pour les deux parties.", "D'un échange à des pactes durables et à la négociation avec une harde.", "Un seul désir perçu, pas toutes les pensées ; votre promesse vous engage."], ["Aile empruntée", "Toucher un partenaire consentant pour manifester l'un de ses modes de déplacement.", "Du vol plané au vrai vol et à la combinaison de partenaires.", "Un seul mode à la fois, limité par votre rang et l'endurance du partenaire."]],
      "ashen-star-covenant": [["Écho de sort", "Après avoir vu un sort complet, le reproduire une fois sans matériau dans l'heure.", "Décomposer puis combiner les structures observées.", "Il faut tout voir ; un seul écho, jamais au-dessus de votre rang."], ["Écriture vivante", "Une rune simple s'ajuste une fois quand son objet bouge ou se brise.", "Adapter sur place armure, porte ou véhicule.", "Conserve seulement l'intention initiale et ne crée pas un second sort."], ["Distance vraie", "En touchant deux objets visibles, connaître le chemin viable le plus court et doubler le prochain pas.", "De la pièce aux portes, murs et coordonnées stellaires.", "Aucun passage mortel inconnu ; seulement votre prochain pas."]],
      "crimson-cauldron": [["Affinité aux mille flammes", "Le premier contact d'une flamme inconnue ne brûle pas immédiatement et révèle l'instant propice pour la dompter.", "Maîtriser plusieurs natures de feu pour l'alchimie et le combat.", "Seulement le premier contact ; ni apprivoisement ni rang ni chaleur durable ne sont annulés."], ["Écho des motifs de pilule", "Après avoir goûté une pilule, reconnaître son ingrédient clé et une erreur de chauffe.", "Corriger puis créer sa propre voie alchimique.", "Un ingrédient et une erreur par pilule, jamais la formule entière."], ["Braise de percée", "Une vraie petite percée laisse trois jours une braise qui rejoue son explosion dans un geste.", "Le geste devient plus décisif avec le rang.", "Une braise par percée, consommée à l'usage ; échec ou déclaration n'en crée pas."]],
      "myriad-mark-hunt": [["Forme véritable double", "Basculer entre une forme qui renforce le corps et une forme-objet.", "Chaque marque reçoit un usage différent dans chaque aspect.", "Un aspect à la fois ; changer interrompt la technique actuelle."], ["Marque autoformée", "Pousser un geste de base à sa limite vérifiable fait naître la marque correspondante sans tuer.", "Les actes vécus deviennent directement des techniques.", "Chaque marque exige un accomplissement limite ; la répétition sûre ne suffit pas."], ["Trait emprunté", "Toucher un noyau non absorbé pour essayer l'un de ses gestes pendant dix souffles.", "Tester la compatibilité puis emprunter un geste rare au moment clé.", "Un geste, non conservé ; la surcharge l'interrompt aussitôt."]],
    },
  },
  es: {
    system: ["El rango fija resistencia, reserva de energía y zonas accesibles; el don altera solo una regla local.", "Una sesión completa puede resumir horas o un día. Todo progreso debe dar una acción utilizable; el avance aún exige su condición real dentro del relato."],
    realms: [["Aprendiz", "Capacidad cercana a una persona adulta; la energía sigue inestable.", "Puede aprender el gesto básico y reconocer la fuente de energía."], ["Primer rango", "La energía se estabiliza y mejora claramente la resistencia.", "Puede usar el don elegido en una acción breve y concreta."], ["Segundo rango", "Mantiene la energía en movimiento y supera a un rival ordinario.", "Puede entrar en zonas de bajo riesgo y actuar sin ayuda."], ["Tercer rango", "La energía actúa a varios pasos y sostiene usos compatibles.", "Puede afrontar una amenaza menor y abrir rutas más peligrosas."], ["Rango superior", "La fuerza se mantiene en combates largos y domina rangos inferiores.", "Puede cruzar grandes obstáculos y tratar con los poderes del mundo."]],
    powers: {
      "cinder-river": [["Eco de brasa", "Tocar calor residual revela un eco breve de su último cambio violento.", "El eco gana duración, capas y uso en movimiento.", "Solo el objeto tocado; no lee mentes, lejos ni futuro. El uso repetido desorienta."], ["Sello de fuerza prestada", "Tras recibir un impacto real, guarda parte de su fuerza en la palma y libérala una vez antes de diez respiraciones.", "Conserva más fuerza y cambia un intercambio cercano.", "Solo un golpe; aún recibes daño y no guarda hechizos, veneno ni fuerza insoportable."], ["Bolsillo del vacío", "Tres veces al día guarda un objeto inerte cubierto por la palma en un espacio inmóvil.", "Aumenta tamaño y rapidez para ocultar, cambiar o superar controles.", "Máximo tres objetos; nada vivo, ardiendo o más pesado que tú."]],
      "sky-beast-isles": [["Ojo celeste compartido", "Una bestia voluntaria comparte brevemente vista y orientación.", "De unos segundos a coordinación mutua durante el vuelo.", "Sin fuerza ni control; miedo o traición rompen el vínculo."], ["Pacto salvaje", "Comprende el deseo más fuerte de una bestia y propone un intercambio que obliga a ambos.", "De un trato a pactos duraderos y negociación con bandadas.", "Solo percibe el deseo principal, no todos los pensamientos; debes cumplir tu parte."], ["Ala prestada", "Toca a un compañero voluntario para manifestar uno de sus movimientos.", "Del planeo al vuelo y a combinar compañeros.", "Un movimiento a la vez, limitado por tu rango y su resistencia."]],
      "ashen-star-covenant": [["Eco de hechizo", "Tras ver un hechizo completo, reprodúcelo una vez sin material durante una hora.", "Descompón y combina estructuras observadas.", "Debes verlo entero; conserva un eco y nunca supera tu rango."], ["Escritura viva", "Una runa básica se ajusta una vez si su objeto se mueve o rompe.", "Adapta armaduras, puertas y vehículos en el lugar.", "Solo preserva la intención original y no crea otro hechizo."], ["Distancia verdadera", "Al tocar dos objetos visibles, conoce el camino viable más corto y duplica tu próximo paso.", "De una sala a puertas, muros y coordenadas estelares.", "No cruza peligros letales desconocidos; solo afecta el próximo paso."]],
      "crimson-cauldron": [["Afinidad de las mil llamas", "El primer contacto de una llama desconocida no quema de inmediato y revela el instante más fácil para domarla.", "Maneja varios fuegos para alquimia y combate.", "Solo evita la primera quemadura; no omite doma, rango ni calor sostenido."], ["Eco del patrón de píldora", "Tras probar una píldora, reconoce su ingrediente clave y un fallo de temperatura.", "Corrige y crea una vía alquímica propia.", "Un ingrediente y un fallo por píldora, nunca la fórmula completa."], ["Brasa de avance", "Un avance menor real deja tres días una brasa que repite su estallido en un movimiento.", "Con más rango, ese movimiento decide más.", "Una brasa por avance, desaparece al usarla; fracaso o palabras no crean nada."]],
      "myriad-mark-hunt": [["Forma verdadera dual", "Alterna entre una forma que refuerza el cuerpo y otra que se vuelve objeto.", "Cada marca obtiene un uso distinto en cada aspecto.", "Solo un aspecto; cambiar interrumpe la técnica actual."], ["Marca autogenerada", "Llevar una acción básica a un límite verificable hace crecer la marca correspondiente sin matar.", "Los actos vividos se convierten en técnicas.", "Cada marca exige un logro límite; la repetición segura no basta."], ["Rasgo prestado", "Toca un núcleo sin absorber para probar uno de sus movimientos durante diez respiraciones.", "Evalúa afinidad y toma un movimiento raro en el momento clave.", "Solo uno y no se conserva; la sobrecarga lo corta."]],
    },
  },
  ar: {
    system: ["تحدد المرتبة القدرة على التحمل ومخزون الطاقة والمناطق الممكنة، بينما تغيّر الموهبة قاعدة محلية واحدة فقط.", "قد تختصر جلسة كاملة ساعات أو يومًا. كل نمو يجب أن يمنح فعلًا قابلًا للاستخدام، ويبقى الاختراق محتاجًا إلى شرطه الحقيقي داخل السرد."],
    realms: [["مبتدئ", "قدرة قريبة من الإنسان البالغ والطاقة ما تزال غير مستقرة.", "يتعلم الحركة الأساسية ويميّز مصدر الطاقة."], ["المرتبة الأولى", "تستقر الطاقة وتتحسن القدرة على التحمل بوضوح.", "يستخدم الموهبة المختارة في فعل قصير وملموس."], ["المرتبة الثانية", "يحافظ على الطاقة أثناء الحركة ويتفوق على خصم عادي.", "يدخل مناطق قليلة الخطر ويتصرف دون مساعدة."], ["المرتبة الثالثة", "تؤثر الطاقة على بعد خطوات وتدعم استخدامات متوافقة.", "يواجه خطرًا صغيرًا منفردًا ويفتح طرقًا أصعب."], ["المرتبة العليا", "تستقر القوة في قتال طويل وتتفوق على المراتب الأدنى.", "يعبر العوائق الكبرى ويتعامل مع القوى المؤثرة في العالم."]],
    powers: {
      "cinder-river": [["صدى الجمر", "يكشف لمس الحرارة الباقية صدى قصيرًا لآخر تغير عنيف أصاب الشيء.", "يطول الصدى وتتعدد طبقاته ويصبح ممكنًا أثناء الحركة.", "يقرأ الشيء الملموس فقط؛ لا أفكار ولا استشعار بعيد ولا تنبؤ، وكثرة الاستخدام تسبب الدوار."], ["ختم القوة المستعارة", "بعد تلقي صدمة حقيقية، تخزن جزءًا من قوتها في الكف وتطلقه مرة خلال عشرة أنفاس.", "تحتفظ بقوة أكبر وتقلب مواجهة قريبة واحدة.", "صدمة واحدة فقط؛ يبقى الضرر ولا يخزن سحرًا أو سمًا أو قوة تفوق الجسد."], ["جيب الفراغ", "ثلاث مرات يوميًا، تخزن جسمًا جامدًا تغطيه الكف كاملًا في حيز ساكن.", "يزداد الحجم والسرعة للإخفاء أو التبديل أو تجاوز التفتيش.", "ثلاثة أشياء كحد أقصى؛ لا حي ولا مشتعل ولا أثقل منك."]],
      "sky-beast-isles": [["عين السماء المشتركة", "يشارك وحش راضٍ بصره وإحساسه بالاتجاه مدة قصيرة.", "من ثوانٍ إلى تنسيق متبادل أثناء الطيران.", "لا إجبار ولا سرقة سيطرة؛ الخوف أو الخيانة يقطعان الرابط."], ["العهد البري", "تفهم أقوى رغبة لوحش وتقترح تبادلًا يلزم الطرفين.", "من صفقة واحدة إلى عهود طويلة وتفاوض مع القطعان.", "تسمع أقوى رغبة فقط لا كل الأفكار، وعليك الوفاء بدورك."], ["الجناح المستعار", "تلمس شريكًا راضيًا لتظهر على جسدك إحدى حركاته.", "من الانزلاق إلى الطيران وتركيب حركات شركاء مختلفين.", "حركة واحدة، محدودة بمرتبتك وتحمل الشريك."]],
      "ashen-star-covenant": [["صدى التعويذة", "بعد مشاهدة تعويذة كاملة، تعيدها مرة بلا مواد خلال ساعة.", "تفكك البنى التي رأيتها ثم تركبها.", "يجب رؤية الإلقاء كاملًا؛ صدى واحد ولا يتجاوز مرتبتك."], ["النقش الحي", "تعدل علامة أساسية نفسها مرة إذا تحرك جسمها أو انكسر.", "تكيّف درعًا أو بابًا أو مركبة في المكان.", "تحافظ على القصد الأصلي فقط ولا تخلق تعويذة ثانية."], ["المسافة الحقيقية", "عند لمس جسمين مرئيين تعرف أقصر طريق ممكن وتجعل خطوتك التالية بطول خطوتين.", "من غرفة إلى أبواب وجدران وإحداثيات نجمية.", "لا تعبر خطرًا قاتلًا مجهولًا وتؤثر في الخطوة التالية فقط."]],
      "crimson-cauldron": [["ألفة آلاف النيران", "أول ملامسة لنار غريبة لا تحرق فورًا وتكشف أسهل لحظة لترويضها.", "تتعامل مع طبائع نار متعددة للكيمياء والقتال.", "تحمي اللمسة الأولى فقط؛ لا تلغي الترويض أو المرتبة أو الحرارة المستمرة."], ["صدى نقش الحبة", "بعد تذوق حبة دواء، تعرف أهم مكون وخطأ واحدًا في الحرارة.", "تصلح الوصفات وتبني طريقك الكيميائي.", "مكوّن وخطأ واحد لكل حبة، وليس الوصفة كاملة."], ["جمرة الاختراق", "يترك اختراق صغير حقيقي جمرة لثلاثة أيام تعيد انفجاره في حركة واحدة.", "يزداد أثر الحركة مع المرتبة.", "جمرة واحدة لكل اختراق وتزول بالاستخدام؛ الفشل أو الادعاء لا يصنعها."]],
      "myriad-mark-hunt": [["الهيئة الأصلية المزدوجة", "تبدّل بين هيئة تقوي الجسد وأخرى تتحول إلى أداة.", "يحصل كل ختم على استخدام مختلف في كل هيئة.", "هيئة واحدة فقط، والتبديل يقطع مهارة الختم الحالية."], ["الختم الذاتي", "إتقان حركة أساسية حتى حد قابل للإثبات ينبت ختمها من دون قتل كائن.", "تتحول الأفعال والتجارب الشخصية إلى مهارات.", "كل ختم يحتاج إنجازًا حقيقيًا عند الحد؛ التكرار الآمن لا يكفي."], ["السمة المستعارة", "تلمس نواة غير ممتصة لتجرب إحدى حركاتها عشرة أنفاس.", "تختبر التوافق وتستعير حركة نادرة في اللحظة الحاسمة.", "حركة واحدة لا تبقى؛ الحمل الزائد يوقفها فورًا."]],
    },
  },
};

const REALM_NAMES = {
  fr: {
    "cinder-river": ["Corps mortel", "Aspiration du qi I", "Aspiration du qi II", "Aspiration du qi III", "Condensation des méridiens"],
    "sky-beast-isles": ["Marcheur terrestre", "Apprenti lié au vent", "Dresseur à un anneau", "Patrouilleur à deux anneaux", "Maître de la couronne nuageuse"],
    "ashen-star-covenant": ["Apprenti sans anneau", "Adepte à un anneau", "Modeleur à deux anneaux", "Marcheur de tour à trois anneaux", "Mage de porte stellaire"],
    "crimson-cauldron": ["Souffle niveau trois", "Souffle niveau quatre", "Roue réunie une étoile", "Maître ardent une étoile", "Roi aérien"],
    "myriad-mark-hunt": ["Premier éveil I", "Formation de marque X", "Double marque XX", "Commandement des marques XL", "Marque couronnée LXX"],
  },
  es: {
    "cinder-river": ["Cuerpo mortal", "Atracción de qi I", "Atracción de qi II", "Atracción de qi III", "Condensación de meridianos"],
    "sky-beast-isles": ["Caminante terrestre", "Aprendiz ligado al viento", "Jinete de un anillo", "Vigía de dos anillos", "Maestro de corona nubosa"],
    "ashen-star-covenant": ["Aprendiz sin anillo", "Adepto de un anillo", "Modelador de dos anillos", "Caminante de torre de tres anillos", "Mago de puerta estelar"],
    "crimson-cauldron": ["Aliento nivel tres", "Aliento nivel cuatro", "Rueda reunida una estrella", "Maestro ardiente una estrella", "Rey celeste"],
    "myriad-mark-hunt": ["Primer despertar I", "Formación de marca X", "Marca doble XX", "Dominio de marcas XL", "Marca coronada LXX"],
  },
  ar: {
    "cinder-river": ["الجسد البشري", "جذب الطاقة الأول", "جذب الطاقة الثاني", "جذب الطاقة الثالث", "تكثيف القنوات"],
    "sky-beast-isles": ["سائر الأرض", "متدرب مربوط بالريح", "فارس الحلقة الواحدة", "حارس الحلقتين", "سيد تاج السحاب"],
    "ashen-star-covenant": ["متدرب بلا حلقة", "متمكن الحلقة الواحدة", "مشكل الحلقتين", "سائر البرج بثلاث حلقات", "ساحر البوابة النجمية"],
    "crimson-cauldron": ["مرحلة النفس الثالثة", "مرحلة النفس الرابعة", "جمع العجلة بنجمة", "سيد اللهب بنجمة", "ملك السماء"],
    "myriad-mark-hunt": ["اليقظة الأولى", "تكوين الختم العاشر", "الختمان العشرون", "قيادة الأختام الأربعون", "الختم المتوج السبعون"],
  },
};

const OPENING_AND_SEED = {
  fr: {
    "cinder-river": ["Marché des remèdes de la porte sud", "La rivière remonte", "Trouver sa voie pendant le blocus, tenter d'aspirer le qi et faire du don le début d'une cultivation", "pièces de cuivre", [["Vieux manteau de toile", "Décoloré mais assez chaud"], ["Pièce de cuivre maternelle", "Une encoche en croissant marque le bord"]], ["La rivière a remonté son cours cette nuit", "La cité est sous blocus temporaire", "La brume dorée signale une marée propice à la perception du qi", "Vous connaissez la respiration rudimentaire mais n'avez jamais retenu le qi"]],
    "sky-beast-isles": ["Port des jeunes bêtes, île Voile-Brisée", "La migration s'emballe", "Obtenir une vraie liberté d'action dans le ciel avant la fermeture de la route", "perles de vent", [["Vieux harnais de vol", "Supporte un court vol ; éviter les fortes rafales"], ["Galettes de mousse douce", "La plupart des jeunes bêtes s'arrêtent pour les sentir"]], ["La cloche de migration a sonné tôt", "La mousse rouge de la bête vient d'une île inconnue", "Le jeune animal n'est lié à personne"]],
    "ashen-star-covenant": ["Objets trouvés, gare nord de Tour-Grise", "La septième étoile s'éteint", "Maîtriser un premier sort personnel et décider comment employer l'indice des disparitions", "écus d'argent", [["Boîte de craies runiques", "Six craies minérales pour trois runes simples"], ["Billet annulé", "Les règles de sécurité sont imprimées au dos"]], ["La septième étoile s'est éteinte cette nuit", "La porte rend les bagages mais pas les voyageurs", "L'académie cache encore l'ampleur de l'accident"]],
    "crimson-cauldron": ["Vieille rue des remèdes, Crête-du-Sud", "La flamme bleue sans maître", "Saisir une occasion réelle de commencer la cultivation ou l'alchimie", "pièces d'or", [["Tonique des méridiens", "Suffit pour un bain médicinal d'une demi-journée"], ["Page copiée de traction du souffle", "Contient l'exercice de traction à distance le plus simple"]], ["Le four public a explosé cette nuit", "Une flamme bleue sans maître est entrée dans les bains", "La guilde ferme la vieille rue"]],
    "myriad-mark-hunt": ["Abri d'examen, village du Chêne-Vert", "Le corne-foudre n'est pas entré", "Prouver un usage réel de sa forme et trouver une première occasion de marque", "pièces de marque", [["Brassard d'entraînement", "Absorbe un choc de perte de contrôle"], ["Viande salée", "Une journée de vivres ou un appât ordinaire"]], ["L'académie a supprimé les places du village", "Le corne-foudre bloque la route sans attaquer", "Le second tonnerre n'était suivi d'aucun rugissement"]],
  },
  es: {
    "cinder-river": ["Mercado medicinal de la puerta sur", "El río corre al revés", "Hallar tu camino durante el cierre, intentar atraer qi y convertir el don en el inicio del cultivo", "monedas de cobre", [["Abrigo de tela gastado", "Descolorido pero suficiente contra el frío"], ["Moneda de tu madre", "Una muesca de media luna marca el borde"]], ["El río invirtió su curso esta noche", "La ciudad está bajo cierre temporal", "La niebla dorada marca una marea apta para sentir qi", "Conoces respiración básica, pero nunca has retenido qi"]],
    "sky-beast-isles": ["Puerto de crías, isla Vela Rota", "La migración se descontrola", "Obtener libertad real en el cielo antes de que cierre la ruta", "cuentas de viento", [["Arnés planeador viejo", "Soporta un planeo corto; evita ráfagas fuertes"], ["Pasteles de musgo dulce", "La mayoría de crías se detienen a olerlos"]], ["La campana migratoria sonó antes", "El musgo rojo procede de una isla desconocida", "La cría no está vinculada a nadie"]],
    "ashen-star-covenant": ["Objetos perdidos, estación norte de Torre Gris", "Se apaga la séptima estrella", "Dominar un primer hechizo propio y decidir cómo usar la pista de los desaparecidos", "escudos de plata", [["Caja de tizas rúnicas", "Seis tizas minerales para tres runas básicas"], ["Billete anulado", "Las normas de seguridad están al dorso"]], ["La séptima estrella se apagó esta noche", "La puerta devuelve equipaje, no viajeros", "La academia aún oculta la escala del accidente"]],
    "crimson-cauldron": ["Calle vieja de medicinas, Cresta Sur", "La llama azul sin dueño", "Aprovechar una oportunidad real para iniciar cultivo o alquimia", "monedas de oro", [["Tónico de meridianos", "Basta para un baño medicinal de medio día"], ["Página copiada de atracción", "Contiene el ejercicio de tracción a distancia más básico"]], ["El horno público explotó esta noche", "Una llama azul entró en los baños viejos", "El gremio está cerrando la calle"]],
    "myriad-mark-hunt": ["Cobertizo de examen, Aldea Roble Verde", "El cuernotrueno no entró", "Probar un uso real de tu forma y encontrar la primera oportunidad de marca", "monedas de marca", [["Brazal de entrenamiento", "Absorbe un impacto por pérdida de control"], ["Carne salada", "Comida de un día o cebo para una bestia común"]], ["La academia canceló las plazas de la aldea", "El cuernotrueno bloquea el camino sin atacar", "El segundo trueno no tuvo rugido"]],
  },
  ar: {
    "cinder-river": ["سوق الدواء عند البوابة الجنوبية", "النهر يجري عكسًا", "اعثر على طريقك أثناء الإغلاق وحاول جذب الطاقة لتجعل الموهبة بداية التدريب", "عملات نحاسية", [["معطف قماشي بالٍ", "باهت لكنه يصد البرد"], ["عملة الأم النحاسية", "شق هلالي عند الحافة"]], ["عكس النهر جريانه الليلة", "المدينة تحت إغلاق مؤقت", "الضباب الذهبي علامة موجة مناسبة لاستشعار الطاقة", "تعرف تنفسًا بدائيًا لكنك لم تحتفظ بالطاقة من قبل"]],
    "sky-beast-isles": ["ميناء الصغار في جزيرة الشراع المكسور", "موسم الهجرة يفلت", "احصل على حرية فعل حقيقية في السماء قبل إغلاق الطريق", "خرز الريح", [["حزام انزلاق قديم", "يتحمل انزلاقًا قصيرًا ويجب تجنب الريح العنيفة"], ["كعك الطحلب الحلو", "تتوقف معظم الوحوش الصغيرة لتشمّه"]], ["قرع جرس الهجرة مبكرًا", "الطحلب الأحمر جاء من جزيرة مجهولة", "الصغير غير مرتبط بأحد"]],
    "ashen-star-covenant": ["قاعة المفقودات في المحطة الشمالية", "انطفاء النجمة السابعة", "أتقن أول تعويذة خاصة بك وقرر كيف تستخدم دليل المفقودين", "دروع فضية", [["علبة طباشير النقوش", "ست قطع معدنية تكفي لثلاث علامات بسيطة"], ["تذكرة ملغاة", "تعليمات أمان البوابة مطبوعة خلفها"]], ["انطفأت النجمة السابعة الليلة", "تعيد البوابة الأمتعة لا المسافرين", "لم تكشف الأكاديمية حجم الحادث"]],
    "crimson-cauldron": ["شارع الدواء القديم في مدينة التلال", "اللهب الأزرق بلا مالك", "اغتنم فرصة حقيقية لبدء التدريب أو الكيمياء", "عملات ذهبية", [["دواء تدفئة القنوات", "يكفي لحمام علاجي نصف يوم"], ["صفحة نسخ لسحب النفس", "تشرح أبسط تدريب للسحب عن بعد"]], ["انفجر الفرن العام الليلة", "دخل لهب أزرق بلا مالك حمام الشارع", "تغلق النقابة شارع الدواء القديم"]],
    "myriad-mark-hunt": ["مظلة الاختبار في قرية السنديان", "وحش قرن الرعد لم يدخل", "أثبت استخدامًا حقيقيًا لهيئتك واعثر على أول فرصة ختم", "عملات الأختام", [["واقي تدريب", "يمتص صدمة واحدة من فقدان السيطرة"], ["لحم مملح", "طعام يوم أو طعم لوحش عادي"]], ["ألغت الأكاديمية مقاعد القرية", "يسد وحش قرن الرعد الطريق من دون هجوم", "جاء الرعد الثاني بلا زئير"]],
  },
};

export function localizePreset(world, language) {
  if (language === "zh") return { ...structuredClone(world), language: "zh" };
  if (language === "en") return applyFullEnglish(world, PRESET_TRANSLATIONS.en[world.id]);
  const head = LANGUAGE_TERMS[language]?.[world.id];
  const generic = GENERIC_TRANSLATIONS[language];
  const opening = OPENING_AND_SEED[language]?.[world.id];
  if (!head || !generic || !opening) return { ...structuredClone(world), language: "zh" };
  const localized = structuredClone(world);
  [localized.title, localized.subtitle, localized.description, localized.genre, localized.tags] = head;
  localized.sourceLabel = world.sourceLabel.includes("同人")
    ? {
      fr: world.id === "crimson-cauldron" ? "Inspiration non officielle · mécanismes de progression de Battle Through the Heavens" : "Inspiration non officielle · mécanismes de progression de Soul Land",
      es: world.id === "crimson-cauldron" ? "Inspiración no oficial · mecánicas de progreso de Battle Through the Heavens" : "Inspiración no oficial · mecánicas de progreso de Soul Land",
      ar: world.id === "crimson-cauldron" ? "إلهام غير رسمي · آليات التطور في Battle Through the Heavens" : "إلهام غير رسمي · آليات التطور في Soul Land",
    }[language]
    : { fr: "Création originale TGN Live", es: "Original de TGN Live", ar: "عمل أصلي من TGN Live" }[language];
  [localized.powerSystem.summary, localized.powerSystem.growth] = WORLD_RULES[language][world.id];
  localized.powerSystem.realms = localized.powerSystem.realms.map((realm, index) => ({ ...realm, name: REALM_NAMES[language][world.id][index], benchmark: REALM_MECHANICS[language][world.id][index][0], unlock: REALM_MECHANICS[language][world.id][index][1] }));
  localized.powers = localized.powers.map((power, index) => { const values = generic.powers[world.id][index]; return { ...power, name: values[0], description: values[1], growth: values[2], boundary: values[3] }; });
  applyOpeningAndSeed(localized, opening, language);
  localized.language = language;
  return localized;
}

function applyFullEnglish(world, translation) {
  const localized = structuredClone(world);
  [localized.title, localized.subtitle, localized.description, localized.genre, localized.tags, localized.sourceLabel] = translation.head;
  localized.powerSystem.summary = translation.system[0];
  localized.powerSystem.growth = translation.system[1];
  localized.powerSystem.realms = localized.powerSystem.realms.map((realm, index) => ({ ...realm, name: translation.system[2][index][0], benchmark: translation.system[2][index][1], unlock: translation.system[2][index][2] }));
  localized.powers = localized.powers.map((power) => { const values = translation.powers[power.id]; return { ...power, name: values[0], description: values[1], growth: values[2], boundary: values[3] }; });
  localized.opening.location = translation.opening[0];
  localized.opening.chapterTitle = translation.opening[1];
  localized.opening.goal = translation.opening[2];
  localized.seed.currencyName = translation.seed.currency;
  localized.seed.inventory = localized.seed.inventory.map((item) => ({ ...item, name: translation.seed.inventory[item.id][0], description: translation.seed.inventory[item.id][1] }));
  localized.seed.relationships = localized.seed.relationships.map((npc) => ({ ...npc, name: translation.seed.relationships[npc.id]?.[0] || npc.name, role: translation.seed.relationships[npc.id]?.[1] || npc.role }));
  localized.seed.capabilities = localized.seed.capabilities.map((ability) => ({ ...ability, name: translation.seed.capabilities[ability.id]?.[0] || ability.name, description: translation.seed.capabilities[ability.id]?.[1] || ability.description, source: translation.seed.capabilities[ability.id]?.[2] || ability.source }));
  localized.seed.facts = translation.seed.facts;
  localized.language = "en";
  return localized;
}

function applyOpeningAndSeed(world, values, language) {
  world.opening.location = values[0];
  world.opening.chapterTitle = values[1];
  world.opening.goal = values[2];
  world.seed.currencyName = values[3];
  world.seed.inventory = world.seed.inventory.map((item, index) => ({ ...item, name: values[4][index][0], description: values[4][index][1] }));
  world.seed.facts = values[5];
  world.seed.relationships = world.seed.relationships.map((npc) => ({ ...npc, name: NPC_NAMES[npc.id]?.[language === 'ar' ? 1 : 0] || npc.name, role: localizeRole(npc.id, language, npc.role) }));
  world.seed.capabilities = world.seed.capabilities.map((ability) => {
    const translated = localizeCapability(ability.id, language, ability);
    return { ...ability, name: translated.name, description: translated.description, source: world.powerSystem.realms[0].name };
  });
}

function localizeRole(id, language, fallback) {
  const roles = {
    fr: { "shen-qiuhua": "marchande de remèdes", "han-zheng": "capitaine de nuit", "mi-ya": "soigneuse de bêtes", "kun-ge": "navigateur déchu", seif: "inspectrice de l'académie", oran: "horloger", "gu-yao": "héritière d'une officine ruinée", "shi-kuo": "mercenaire manchot", "du-heng": "chef du village", "a-chi": "jeune chasseur" },
    es: { "shen-qiuhua": "mercader de medicinas", "han-zheng": "capitán nocturno", "mi-ya": "sanadora de bestias", "kun-ge": "navegante caído", seif: "inspectora de la academia", oran: "relojero", "gu-yao": "heredera de una botica arruinada", "shi-kuo": "mercenario manco", "du-heng": "jefe de aldea", "a-chi": "cazador joven" },
    ar: { "shen-qiuhua": "صاحبة متجر دواء", "han-zheng": "قائد الحرس الليلي", "mi-ya": "معالجة الوحوش", "kun-ge": "ملاح فقد مكانته", seif: "مفتشة الأكاديمية", oran: "صانع ساعات", "gu-yao": "وريثة صيدلية مفلسة", "shi-kuo": "مرتزق بذراع واحدة", "du-heng": "رئيس القرية", "a-chi": "صياد شاب" },
  };
  return roles[language]?.[id] || fallback;
}

function localizeCapability(id, language, fallback) {
  const values = {
    fr: { "short-glide": ["Vol plané court", "Le vieux harnais franchit une dizaine de pas depuis une hauteur ; le vent turbulent reste dangereux."], "read-basic-runes": ["Lire les runes simples", "Reconnaît activation, arrêt et danger, sans pouvoir encore lancer un sort seul."], "sense-flame": ["Sentir le souffle de flamme", "Les yeux fermés, repère le souffle le plus fort à quelques pas sans connaître son maître."], "manifest-form": ["Manifester la forme véritable", "Maintient la forme choisie plus de dix souffles et utilise son trait le plus simple."] },
    es: { "short-glide": ["Planeo corto", "El arnés viejo cruza unos diez pasos desde una altura; el viento turbulento sigue siendo peligroso."], "read-basic-runes": ["Leer runas básicas", "Reconoce inicio, parada y peligro, pero aún no lanza hechizos sin ayuda."], "sense-flame": ["Sentir aliento ígneo", "Con los ojos cerrados localiza el aliento más fuerte a varios pasos, no a su dueño."], "manifest-form": ["Manifestar forma verdadera", "Mantiene la forma elegida más de diez respiraciones y usa su rasgo más básico."] },
    ar: { "short-glide": ["انزلاق قصير", "يعبر الحزام القديم نحو عشر خطوات من مكان مرتفع، وتبقى الريح المضطربة خطرة."], "read-basic-runes": ["قراءة النقوش البسيطة", "يميّز علامات البدء والتوقف والخطر، لكنه لا يلقي تعويذة منفردًا بعد."], "sense-flame": ["استشعار نفس اللهب", "بعينين مغمضتين يحدد أقوى نفس لهب على بعد خطوات من دون معرفة مالكه."], "manifest-form": ["إظهار الهيئة الأصلية", "يحافظ على الهيئة المختارة أكثر من عشرة أنفاس ويستخدم أبسط سماتها."] },
  };
  const translated = values[language]?.[id];
  return translated ? { name: translated[0], description: translated[1] } : fallback;
}
